/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotebookRouteRouteImport } from './routes/notebook/route'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as NotebookIndexRouteImport } from './routes/notebook/index'
import { Route as NotebookIdRouteImport } from './routes/notebook/$id'
import { Route as AuthAuthLoginRouteImport } from './routes/auth/auth/login'
import { Route as AuthAuthRegisterRouteImport } from './routes/auth/auth/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRouteRoute = NotebookRouteRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookIndexRoute = NotebookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotebookRouteRoute,
} as any)
const NotebookIdRoute = NotebookIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NotebookRouteRoute,
} as any)
const AuthAuthLoginRoute = AuthAuthLoginRouteImport.update({
  id: '/auth/auth/login',
  path: '/auth/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthRegisterRoute = AuthAuthRegisterRouteImport.update({
  id: '/auth/auth/register',
  path: '/auth/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notebook': typeof NotebookRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/notebook/$id': typeof NotebookIdRoute
  '/notebook/': typeof NotebookIndexRoute
  '/auth/auth/login': typeof AuthAuthLoginRoute
  '/auth/auth/register': typeof AuthAuthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/notebook/$id': typeof NotebookIdRoute
  '/notebook': typeof NotebookIndexRoute
  '/auth/auth/login': typeof AuthAuthLoginRoute
  '/auth/auth/register': typeof AuthAuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notebook': typeof NotebookRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/notebook/$id': typeof NotebookIdRoute
  '/notebook/': typeof NotebookIndexRoute
  '/auth/auth/login': typeof AuthAuthLoginRoute
  '/auth/auth/register': typeof AuthAuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notebook'
    | '/auth/login'
    | '/auth/register'
    | '/notebook/$id'
    | '/notebook/'
    | '/auth/auth/login'
    | '/auth/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/notebook/$id'
    | '/notebook'
    | '/auth/auth/login'
    | '/auth/auth/register'
  id:
    | '__root__'
    | '/'
    | '/notebook'
    | '/auth/login'
    | '/auth/register'
    | '/notebook/$id'
    | '/notebook/'
    | '/auth/auth/login'
    | '/auth/auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotebookRouteRoute: typeof NotebookRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthAuthLoginRoute: typeof AuthAuthLoginRoute
  AuthAuthRegisterRoute: typeof AuthAuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook/': {
      id: '/notebook/'
      path: '/'
      fullPath: '/notebook/'
      preLoaderRoute: typeof NotebookIndexRouteImport
      parentRoute: typeof NotebookRouteRoute
    }
    '/notebook/$id': {
      id: '/notebook/$id'
      path: '/$id'
      fullPath: '/notebook/$id'
      preLoaderRoute: typeof NotebookIdRouteImport
      parentRoute: typeof NotebookRouteRoute
    }
    '/auth/auth/login': {
      id: '/auth/auth/login'
      path: '/auth/auth/login'
      fullPath: '/auth/auth/login'
      preLoaderRoute: typeof AuthAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/auth/register': {
      id: '/auth/auth/register'
      path: '/auth/auth/register'
      fullPath: '/auth/auth/register'
      preLoaderRoute: typeof AuthAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NotebookRouteRouteChildren {
  NotebookIdRoute: typeof NotebookIdRoute
  NotebookIndexRoute: typeof NotebookIndexRoute
}

const NotebookRouteRouteChildren: NotebookRouteRouteChildren = {
  NotebookIdRoute: NotebookIdRoute,
  NotebookIndexRoute: NotebookIndexRoute,
}

const NotebookRouteRouteWithChildren = NotebookRouteRoute._addFileChildren(
  NotebookRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotebookRouteRoute: NotebookRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthAuthLoginRoute: AuthAuthLoginRoute,
  AuthAuthRegisterRoute: AuthAuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
